Sprint
gostuding/GophKeeper pull request #1
Opened 2023-10-22 20:48 UTC by gostuding

2023-11-01 07:27 UTC, s-shpak requested changes
Я час читал код и очень плохо его понял. Из формальных претензий:
- нет реализации локального кеша
- нет сохранения паролей
- нет офлайн режима

Код организован очень путано, я не вижу в нем структуры, из-за чего очень сложно судить о том, что он делает.

Я очень рекомендую тебе взять 1-1, потому что в таком виде я не смогу принять проект

2023-11-01 07:27 UTC, s-shpak commented on cmd/agent/main.go
> +	fmt.Fprintf(os.Stdout, "Version: %s, date: %s, commit: %s\n", version, date, commit)
Почему бы не использовать логгер?

2023-11-01 07:27 UTC, s-shpak commented on cmd/agent/main.go
> +	"log"
Не стоит использовать стандартный логгер

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +func makeError(t errType, values ...any) error {
1. Это неидиоматичный подход к работе с ошибками в го: не обяъвляй отдельный `errType`, а просто объяви необходимые ошибки и правильно оберни их
2. Форматирование строк не очень удобно: откуда мы знаем, что в `values` - только одно значение?

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +	Storage interface {
Почему интерфейс взаимодействия с сервисом называется `Storage` ? `Storage` - это же какое-то хранилище? Почему тогда в нем определены такие методы как `Authentification` или `ServerAESKey` ?

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +		Check(string) error
Есть смысл называть аргументы в интерфейсе: это делает код понятнее

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +		mutex          sync.Mutex
Когда работаешь с мютексами лучше всегда использовать указатели

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +		ctx            context.Context //nolint:containedctx //<-
Контекст не стоит хранить в объекте, его лучше передавать первым аргументом функции

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +	"github.com/howeyc/gopass"
Этот репозиторий больше не поддерживается, его не надо использовать

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +		isRun          bool // flag that agent is run
Зачем нужно это поле?

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +func (a *Agent) Run() error {
Может быть можно как-то зарефаторить этот метод, пока он довольно плохо читаем

2023-11-01 07:27 UTC, s-shpak commented on README.md
> +# Перед запуском сервера проверить наличие
Так не пойдет: это должно быть полностью автоматизировано. Максимум, что можно потребовать от пользователя - запустить Postgres локально и передать сетевой сокет, через который к СУБД можно подключиться (желательно, конечно, использовать Docker контейнер, но требовать я это не могу)

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent.go
> +func (a *Agent) parceCommand(cmd string) string {
Логику твоего TUI очень сложно читать. Я бы посоветовал тебе не использовать TUI, а остановиться на CLI. Если ты все же хочешь использовать TUI, то я бы посоветовал взять стороннюю библиотеку. Если ты хочешь оставить самописную логику, то ее надо отрефакторить

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/agent_test.go
Нужны тесты TUI

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/example_test.go
> +	fmt.Printf("Agent create success. Run status: %v", agent.IsRun())
Как можно увидеть этот вывод?

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/example_test.go
> +	if err != nil {
При этом тест все равно закончится успешно

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/storage/network.go
> +		ServerPublicKey *rsa.PublicKey  // public server key for encrypt messages
Это плохой подход: генерируй сертификаты и утсанавливай TLS-соединение между клиентом и сервером

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/storage/network.go
> +func (ns *NetStorage) AddFile(url, fPath string, fid int) error {
Не стоит изобретать велосипед: если файл большой, то посылай его, используя HTTP-stream

2023-11-01 07:27 UTC, s-shpak commented on internal/agent/storage/network.go
> +func (ns *NetStorage) FihishFileTransfer(url string, fid int) error {
При имплементации через HTTP-stream эта функция не нужна

2023-11-03 22:27 UTC, gostuding commented on internal/agent/agent.go
> +func (a *Agent) Run() error {
Переделал

2023-11-03 22:28 UTC, gostuding commented on internal/agent/agent.go
> +		isRun          bool // flag that agent is run
Убрал ненужные поля

2023-11-03 22:28 UTC, gostuding commented on internal/agent/agent.go
> +		ctx            context.Context //nolint:containedctx //<-
Убрано

2023-11-03 22:28 UTC, gostuding commented on internal/agent/agent.go
> +		mutex          sync.Mutex
Убрано

2023-11-03 22:33 UTC, gostuding commented on cmd/agent/main.go
> +	fmt.Fprintf(os.Stdout, "Version: %s, date: %s, commit: %s\n", version, date, commit)
а зачем? Почему бы не использовать fmt?

2023-11-03 22:33 UTC, gostuding commented on cmd/agent/main.go
> +	"log"
Почему? Чем он плох для вывода ошибки работы программы?

2023-11-03 22:54 UTC, gostuding commented on README.md
> +# Перед запуском сервера проверить наличие
Не могу понять, что значит "передать сетевой сокет"?
Здесь просто описано, что должна стоять СУБД, в ней создана БД и пользователь! Что не так? Как пользователю будет удобно, пусть так и делает: ставит локально, на отдельный сервер, в Docker контейнер и т.п.

2023-11-03 22:54 UTC, gostuding commented on internal/agent/agent.go
> +func (a *Agent) parceCommand(cmd string) string {
Переделал

2023-11-03 22:54 UTC, gostuding commented on internal/agent/agent_test.go
Переделано

2023-11-03 23:19 UTC, gostuding commented on internal/agent/example_test.go
> +	fmt.Printf("Agent create success. Run status: %v", agent.IsRun())
Изменить в тесте значение Output: и проверить что вывод такой.

2023-11-03 23:20 UTC, gostuding commented on internal/agent/example_test.go
> +	if err != nil {
Тест переделан

2023-11-03 23:20 UTC, gostuding commented on internal/agent/storage/network.go
> +		ServerPublicKey *rsa.PublicKey  // public server key for encrypt messages
Переделал

2023-11-03 23:46 UTC, gostuding commented on internal/agent/storage/network.go
> +func (ns *NetStorage) AddFile(url, fPath string, fid int) error {
Оставлю так, потому что вижу в этом методе некоторые возможности по сравнению с HTTP-stream.

2023-11-03 23:47 UTC, gostuding commented on internal/agent/storage/network.go
> +func (ns *NetStorage) FihishFileTransfer(url string, fid int) error {
Оставлю как есть. Согласно ТЗ: "Функции, реализация которых остаётся на усмотрение исполнителя: протокол взаимодействия клиента и сервера;"

2023-11-03 23:56 UTC, gostuding commented on internal/agent/agent.go
> +func makeError(t errType, values ...any) error {
1. Постараюсь переделать.
2. В том, что values может быть не одним и заключается удобство. Если оно одно, то вывод будет такой как описано в форматировании, а если несколько, то fmt их выведет дополнительно, что позволит найти именно то место, где ошибка. Именно поэтому и используется values...

2023-11-04 00:03 UTC, gostuding commented on internal/agent/agent.go
> +	Storage interface {
С точки зрения агента, это хранилище. Агент знает, что в нем можно авторизоваться и для формирования своего ключа шифрования он может запросить ключ у хранилища. Это именно интерфейс, т.к. может быть прослойкой для хранения данных на сервере (как это реализовано), или прослойкой для хранения данных в файле (это можно реализовать далее). Если смущает название, то могу переименовать.

2023-11-04 00:13 UTC, gostuding commented on internal/agent/agent.go
> +	"github.com/howeyc/gopass"
Перенёс код репозитория в проект

2023-11-10 13:32 UTC, gostuding commented on internal/agent/agent.go
> +	"github.com/howeyc/gopass"
Обновил код в соответствии с golint

2023-11-10 14:55 UTC, s-shpak requested changes
1. Код TUI смешан с кодом бизнес-логики, это приводит к спагети-коду. Логика и TUI должны быть очень четко разделены, для этого можно, например, использовать MVC-подход
2. Ты добавил шифрование файлов, но нигде не описано, как управлять ключами. Что если ключ пользователя будут скомпрометирован? Что если разные файлы будут зашифрованы разными ключами?
3. Я не понял, зачем тебе кэш и local storage? чем они отличаются?

2023-11-10 14:55 UTC, s-shpak commented on README.md
> +# Перед запуском сервера проверить наличие
Пользователь, как и я, не должен ничего создавать руками: БД, пользователя и т.д. Все должно создаваться либо автоматически, либо ты должен добавить инструкции по тому, как это делать

2023-11-10 14:55 UTC, s-shpak commented on cmd/agent/main.go
> +	"log"
См. спринт 2

2023-11-10 14:55 UTC, s-shpak commented on cmd/agent/main.go
> +	fmt.Fprintf(os.Stdout, "Version: %s, date: %s, commit: %s\n", version, date, commit)
См. спринт 2

2023-11-10 14:55 UTC, s-shpak commented on internal/server/handlers.go
> +func GetCertificate(p string) ([]byte, error) {
Зачем это ?

2023-11-10 14:55 UTC, s-shpak commented on internal/agent/agent.go
> +	saveLocal, err := a.isSaveInLocal(a.RStorage.GetAESKey(a.Config.Key, a.url(urlAESKey)))
1. Если данные можно сохранить локально в условии недоступности сервсиса, то как они будут синхронизированы с сервером, когда соединение вновь появится?
2. Как решается проблема записи в оффлайн-режиме одних и тех же данны разными клиентами ?

2023-11-10 14:55 UTC, s-shpak commented on internal/agent/agent.go
> +	case "files_get", "cards_get", "data_get", "creds_get":
Получение данных должно выглядеть иначе:
1. Данные могут быть версионированы, анчала необходимо получить с сервера текущую версию данных
2. Если версия совпадает с версией в кеше, то достаем данные из кеша
3. Если нет, то загружаем их с сервера и записываем в кеш

2023-11-10 14:55 UTC, s-shpak commented on internal/agent/storage/network.go
> +		res, err := ns.Client.Do(req)
Если одна из частей файла не скачается, то нам надо перекачивать весь файл?

Если пользователь прервет загрузку, то скачанное останется в файле?

2023-11-10 15:04 UTC, gostuding commented on internal/agent/storage/network.go
> +		res, err := ns.Client.Do(req)
Да

Да

2023-11-10 15:06 UTC, gostuding commented on internal/server/handlers.go
> +func GetCertificate(p string) ([]byte, error) {
Для получения сертификата сервера

2023-11-10 15:07 UTC, gostuding commented on internal/agent/agent.go
> +	saveLocal, err := a.isSaveInLocal(a.RStorage.GetAESKey(a.Config.Key, a.url(urlAESKey)))
Для синхронизации есть отдельная команда

2023-11-10 15:12 UTC, gostuding commented on internal/agent/agent.go
> +	case "files_get", "cards_get", "data_get", "creds_get":
Прикольно, а в задании нельзя было это написать?

2024-05-23 19:51 UTC, closed without merging